### ISSUE TITLE
[joss-review] Where are the tests?

### ISSUE THREAD

**Issue by bmagyar** [CoreRobotics/CoreRobotics#2]
I've found a few files named `test_X` in the `utils` folder but they are not really tests, they just print a bunch of stuff. I ran a `grep` for asserts but could only find one.

Please use a C++ testing framework to implement functional tests with asserts. GTest is usually a good choice.

**Comment by CoreRobotics** [comment]
We're in the process of changing the test scripts to use GTest.  If GTest is not found during the CMake check, then the tests won't build but the rest of the library will.

See: https://github.com/CoreRobotics/CoreRobotics/commit/f623daab14457bb961803dbb0b78843b027a0660

**Comment by CoreRobotics** [comment]
Created a pull request at [https://github.com/CoreRobotics/CoreRobotics/pull/8](https://github.com/CoreRobotics/CoreRobotics/pull/8).

We added in tests using the gtest framework.  Most of the commits in the pull request are related to this.

**Comment by CoreRobotics** [comment]
@bmagyar  thank you for suggesting the gtest framework - it is a really nice package.

-Parker

**Comment by bmagyar** [comment]
Brilliant! Thumbs up for pushing it through, this will help you keep the library alive for long with ease.
