### ISSUE TITLE
[joss-review] Avoid passing around CRManipulator raw pointers

### ISSUE THREAD

**Issue by bmagyar** [CoreRobotics/CoreRobotics#6]
Use any smart pointer from C++11 or (better suited for this use-case) const references to such an object.

**Comment by CoreRobotics** [comment]
Created a pull request at [https://github.com/CoreRobotics/CoreRobotics/pull/8](https://github.com/CoreRobotics/CoreRobotics/pull/8).

We changed the CRManipulator raw pointers to const refs.  See commit [https://github.com/CoreRobotics/CoreRobotics/pull/8/commits/2cad7683c99a73e29e9416e574e97c383f85691c](https://github.com/CoreRobotics/CoreRobotics/pull/8/commits/2cad7683c99a73e29e9416e574e97c383f85691c)

**Comment by bmagyar** [comment]
:+1:
