### ISSUE TITLE
[joss-review] Simplification for code style

### ISSUE THREAD

**Issue by bmagyar** [CoreRobotics/CoreRobotics#7]
...although magnitude of this change may be big.

Example: 
`CoreRobotics::CRClock`

Why the CR prefix? The namespace is already an excellent tag for it. Probably the namespaces were added after the core classes of the library but this simplification step wasn't done. This affect all classes I believe.

**Comment by CoreRobotics** [comment]
Inclusion of CR was to avoid name conflicts before the namespace was introduced.  Unfortunately, this change would significantly impact existing projects.
