### ISSUE TITLE
[joss-review] Missing DOI entries from bib items

### ISSUE THREAD

**Issue by bmagyar** [CoreRobotics/CoreRobotics#9]
Google Scholar doesn't provide this with their bibtex export but JOSS requires the doi field to be filled for bibliography entries. Please look them up and add them.

Ref: https://github.com/openjournals/joss-reviews/issues/489

**Comment by CoreRobotics** [comment]
Quite a few of the references are books that seem to not have DOIs or ISBN-A's that I can find, but they do have regular ISBNs.  What is needed for these cases?  I couldn't find anything on the JOSS site about it.

**Comment by bmagyar** [comment]
Using the ISBN is a good idea. It serves the same purpose after all.

**Comment by CoreRobotics** [comment]
Is it ok to just use the ISBN field in the bib entry for these cases or does the DOI field need to have a value?

**Comment by CoreRobotics** [comment]
See pull request: [https://github.com/CoreRobotics/CoreRobotics/pull/10](https://github.com/CoreRobotics/CoreRobotics/pull/10)

**Comment by CoreRobotics** [comment]
When we include the isbn field in the bib, the joss compiler does not display the number.  Putting it in the doi field would create a broken link.  Any workaround?

See: [https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf](https://github.com/openjournals/joss-papers/blob/joss.00489/joss.00489/10.21105.joss.00489.pdf)

**Comment by bmagyar** [comment]
@danielskatz , could you help us out with this please?

**Comment by danielskatz** [comment]
If there is a DOI for a work, then it should be part of the .bib entry.  If there is no DOI, then use whatever identifier exists.  If there is no field for it, you can always use note={ISBN: xxxxx}

The intent of this checklist item was to fix the problem where people put in bib entries with minimal information that doesn't include existing identifiers, which are DOIs for most papers.

**Comment by CoreRobotics** [comment]
Okay thanks. All the bib entries have DOI or ISBN. ISBNs are not displayed in the generated pdf.  If that's ok, this should be closed.

**Comment by danielskatz** [comment]
it's ok, but would probably be better if the ISBNs were added as notes, and did display

**Comment by bmagyar** [comment]
Thanks! :+1:
